### ISSUE TITLE
Errno checking

### ISSUE THREAD

**Issue by dsheets** [dsheets/ocaml-unix-unistd#7]
We should probably use something like [`Errno_unix.raise_on_errno`](https://github.com/dsheets/ocaml-unix-errno/blob/master/unix/errno_unix.mli#L24).

**Comment by yallop** [comment]
This is complete: we [use](https://github.com/dsheets/ocaml-unix-unistd/blob/a7c941d53ff987172336daa6da7bf384c4b2d10c/unix/unistd_unix.ml#L58-L61) `Errno_unix.raise_errno`.
