### ISSUE TITLE
Update library structure

### ISSUE THREAD

**Issue by dsheets** [dsheets/ocaml-unix-unistd#8]
This library needs to be converted to the same layout as [ocaml-unix-errno](https://github.com/dsheets/ocaml-unix-errno), [ocaml-unix-fcntl](https://github.com/dsheets/ocaml-unix-fcntl), [ocaml-unix-sys-stat](https://github.com/dsheets/ocaml-unix-sys-stat), and [ocaml-unix-dirent](https://github.com/dsheets/ocaml-unix-errno). A common layout, naming, &c helps users intuit the use of the interface.

**Comment by yallop** [comment]
Can this be closed?

**Comment by dsheets** [comment]
LGTM
